### ISSUE TITLE
このアプリを作成した背景を知りたい

### ISSUE THREAD

**Issue by yoshikouki** [kota111/lives#5]
私はPHP（Laravelは特に）分からないので、就職の観点からレビューです！

とても見やすい README が作ってあり、「このリポジトリはこういうアプリで、こんなことができて、こういう技術を採用しているんだな」ということがひと目で分かる内容でした
特にイメージ画像と構成図の写真がとびきり Good でした！

ただ、こちらのリポジトリは転職活動のパートナーとしての役割もあるようですね
その視点でレビューさせていただきましたが、README を通して確かにアプリのことは分かったのですが、一方で @kota111 さんのヒトが見えてこなかったです

以下の点が分かるようになると更に良いパートナーになると思うので、追加されてみてはいかがでしょうか

- なぜこのアプリを作ったのか
- アプリを作る上で苦労した点・工夫した点・アピールしたい点
- 製作期間（具体的に発案・企画・計画・技術選定・調査・実装・検証など細かくわかれば、なお Good!!!）
- レスポンシブデザインが分かるスマホ画面

全て書く必要はないかと思いますが、片平さんの人となりが分かるような内容になったらもっと素敵になると思います！
ファイト！

**Comment by kota111** [comment]
レビュー、本当にありがとうございます！
>なぜこのアプリを作ったのか
>アプリを作る上で苦労した点・工夫した点・アピールしたい点
>製作期間（具体的に発案・企画・計画・技術選定・調査・実装・検証など細かくわかれば、なお Good!!!）
>レスポンシブデザインが分かるスマホ画面

上記の点について、READMEにて、「なぜこのアプリを作ったのか」「製作期間及び苦労した点」「レスポンシブ対応」として、加筆いたしました。
お時間あるときに見ていただけると幸いです。

**Comment by yoshikouki** [comment]
ものすごく詳細に書かれていて、試行錯誤されたことがよく分かるとてもいい内容になりました！
#

後は見出しの優先順位（誰に対してどの情報から優先的に見てほしいのか）が検討されていて、現在の順番で間違いないのであればこの Issue はクローズにしてもらって結構です！

お疲れ様でした！

**Comment by kota111** [comment]
ご指摘いただいたことを参考に見出しの優先順位を変えました（「作成にあたって」と「主な使用技術」を交換しました）
細かいところまで見ていただいて、本当にありがとうございました！

**Comment by kota111** [comment]
ご指摘いただいたことを参考に見出しの優先順位を変えました（「作成にあたって」と「主な使用技術」を交換しました）
細かいところまで見ていただいて、本当にありがとうございました！
